### ISSUE TITLE
Where is DatasetBaby?

### ISSUE THREAD

**Issue by cclauss** [DiligentPanda/Tencent_Ads_Algo_2018#1]
I was not able to find it in this repo:
* <sub>https://github.com/DiligentPanda/Tencent_Ads_Algo_2018/search?q=DatasetBaby&unscoped_q=DatasetBaby</sub>

[flake8](http://flake8.pycqa.org) testing of https://github.com/DiligentPanda/Tencent_Ads_Algo_2018 on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./src/dataset/dataset_youth_r.py:411:15: F821 undefined name 'DatasetBaby'
    dataset = DatasetBaby(users,u_feat_infos,ads,a_feat_infos,data_list,config["feat"]["u_enc"])
              ^
1     F821 undefined name 'DatasetBaby'
1
```

**Comment by DiligentPanda** [comment]
The codes following `if __name__=="__main__"` are old codes that we forget to delete. They are unnecessary.
